language: elixir

dist: trusty

sudo: required

notifications:
  email: false

before_install:
  - curl -L -o /tmp/consul.zip https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
  - unzip /tmp/consul.zip
  - ./consul agent -config-file consul-test.json > /tmp/consul.log &
  - sleep 5

elixir:
  - 1.4.5
  - 1.5.1

otp_release:
  - 20.0
  - 19.3
  - 18.3

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
